config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :tasks do
    collection do
      get :delete_all, :delete_completed
    end
  end
  root "pages#home"
  resources :users, except: [:index, :new]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  get "signup", to: "users#new"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/task.rb
class Task < ApplicationRecord
  validate :category_count_within_bounds

  belongs_to :user
  has_many :task_categories
  has_many :categories, through: :task_categories
  validates_length_of :categories, maximum: 3
  validates :name, presence: true, length: { minimum: 3, maximum: 100 }
  validates :priority, presence: true
  validates :deadline, presence: true
  validates :user_id, presence: true

  private

  def category_count_within_bounds
    errors.add(:base, "Too many categories") if self.categories.count > 3
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :require_user
  before_action :set_task, only: [:edit, :update, :destroy]

  def index
    completed = params[:completed] == "1" ? true : false if params[:completed].present? 

    @tasks = current_user.tasks

    @tasks = @tasks.joins(:task_categories).where(task_categories: {category_id: params[:category_id].to_i}) if params[:category_id].present?
    @tasks = @tasks.where("name LIKE ?", "%#{params[:search]}%") if params[:search].present?
    @tasks = @tasks.where(completed: completed) if params[:completed].present?
    @tasks = @tasks.where(priority: params[:priority]) if params[:priority].present?

    @tasks = @tasks.paginate(page: params[:page], per_page: 50)
  end

  def new
    @task = Task.new
  end

  def edit
  end

  def create
    @task = current_user.tasks.new(task_params)
    if @task.save
      flash[:success] = "Task created!"
      redirect_to tasks_path
    else
      flash[:danger] = "Task failed: #{@task.errors.full_messages}"
      redirect_back(fallback_location: root_url)
    end
  end

  def update
    if @task.update(task_params)
      flash[:success] = "Task updated!"
      redirect_to tasks_path
    else
      flash[:danger] = "Task update failed: #{@task.errors.full_messages}"
      redirect_back(fallback_location: root_url)
    end
  end

  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def delete_all
    current_user.tasks.delete_all
    flash[:success] = "Task updated!"
    redirect_back(fallback_location: root_url)
  end

  def delete_completed
    current_user.tasks.where(completed: true).delete_all
    flash[:success] = "Deleted completed"
    redirect_back(fallback_location: root_url)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_task
    @task = Task.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def task_params
    params.require(:task).permit(:name, :priority, :completed, :deadline, category_ids: [])
  end

end

app/helpers/tasks_helper.rb
module TasksHelper

  def handle_deadline(deadline)
    day = (deadline - Date.today).to_i
    if day > 0
      return pluralize(day, "day")
    elsif day == 0
      return "TODAY"
    else
      return "OVERDUE"
    end
  end
end

app/views/tasks/_filter.html.erb
<%= link_to 'Delete All', delete_all_tasks_path, data: { confirm: 'Are you sure?' } %>
<%= link_to 'Delete Completed', delete_completed_tasks_path, data: { confirm: 'Are you sure?' } %>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :task_name %>
  </div>

  <div class="field">
    <%= form.label :priority %>
    <div class="flexbox">
      <%= form.radio_button :priority, 0, checked: true %><%= form.label "Low" %>
      <%= form.radio_button :priority, 1 %><%= form.label "Mid" %>
      <%= form.radio_button :priority, 2 %><%= form.label "High" %>
    </div>
  </div>

  <div class="field">
    <%= form.label :completed %>
    <%= form.check_box :completed, id: :task_completed %>
  </div>

  <div class="field">
    <%= form.label :deadline %>
    <%= form.date_select :deadline, default: Date.today, id: :task_deadline %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= link_to 'New Category', new_category_path %><br />
    <%= form.collection_select(:category_ids, current_user.categories.all, :id, :name, { prompt: "Can be Empty or Multiple"}, {multiple: true, size: 5, class: "custom-select"}) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<div class="flickr_pagination">
  <%= will_paginate tasks, :container => false %>
</div>

<table>
  <thead>
    <tr>
      <th>Priority</th>
      <th>Completed</th>
      <th>Category</th>
      <th>Name</th>
      <th>Deadline</th>
      <th>Remaining</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% tasks.each do |task| %>
      <tr>
        <td><%= task.priority == 0 ? "Low" : task.priority == 1 ? "Mid" : "High" %></td>
        <td>
          <%= form_with(model: task, local: true) do |form| %>
            <%= form.check_box :completed, onchange: "this.form.submit();" %>
          <% end %>
        </td>
        <td>
          <% if task.categories.any? %>
            <%= render task.categories %>
          <% end %>
        </td>
        <td><%= task.name %></td>
        <td><%= task.deadline %></td>
        <td><%= handle_deadline(task.deadline) %></td>
        <% if logged_in? && task.user == current_user %>
          <td><%= link_to 'Edit', edit_task_path(task) %></td>
          <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>


<div class="flickr_pagination">
  <%= will_paginate tasks, :container => false %>
</div>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tasks</h1>

<span>Task count :</span><%= current_user.tasks.count %>
<span>Completed count :</span><%= current_user.tasks.where(completed: true).count %>

<br/>
<%= link_to 'New Task', new_task_path %>
<%= render 'filter', tasks: @tasks %>

<%= form_with(url: "tasks", method: "get", local: true) do |form| %>
  <%= form.select :category_id, options_from_collection_for_select(current_user.categories, :id, :name), prompt: "Filter categories" %>

  <%= form.text_field :search %>

  <div class="flexbox">
    <%= form.label :completed %>
    <%= form.radio_button :completed, 1 %><%= form.label "True" %>
    <%= form.radio_button :completed, 0 %><%= form.label "False" %>
  </div>

  <div class="flexbox">
    <%= form.label :priority %>
    <%= form.radio_button :priority, 0 %><%= form.label "Low" %>
    <%= form.radio_button :priority, 1 %><%= form.label "Mid" %>
    <%= form.radio_button :priority, 2 %><%= form.label "High" %>
  </div>

  <%= form.submit "search" %>
<% end %>

<%= render 'task', tasks: @tasks %>

<br>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @task.priority %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @task.completed %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @task.deadline %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>