config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :tasks do
    collection do
      get :delete_all, :delete_completed
    end
  end
  root "pages#home"
  resources :users, except: [:index, :new]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  get "signup", to: "users#new"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_error_messages.html.erb
  <% if obj.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(obj.errors.count, "error") %> prohibited this <%= obj %> from being saved:</h2>

      <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

app/views/layouts/_footer.html.erb
<footer>
  <small>Copyright &copy; <%= link_to "Starcloud", "https://helenxfu.github.io/" %></small>
</footer>

app/views/layouts/_navigation.html.erb
<nav>
  <div class="nav_language-option">
    <span>English</span>
    <span class="divider">/</span>
    <span>日本語</span>
    <span class="divider">/</span>
    <span>中文</span>
  </div>
  <%= link_to "Home", root_path %>
  <%= link_to "Categories", categories_path %>
  <%= link_to "Tasks", tasks_path %>

  <div>
    <% if logged_in? %>
      <%= link_to current_user.username, user_path(current_user) %>
      <%= link_to "Logout", logout_path, method: :delete %>
    <% else %>
      <%= link_to "Login", login_path %>
      <%= link_to "Signup", signup_path %>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %><%= " | " if :title != "" %>Task Manager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div>
      <% flash.each_with_index do |message, i| %>
        <div class="flash-msg alert alert-<%= message[0] %>">
          <%= message[1] %>
          <button class="close-btn" onclick="document.getElementsByClassName('flash-msg')[<%= i %>].style.display='none'">
            <span>&times;</span>
        </button>
        </div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>